% grd_mex (called via grd)
%
% Petter Strandmark 2012
% petter@maths.lth.se
function varargout = grd_mex(varargin)

	% -------------------------------------------
	% Modify these!
	coinincludedir = 'C:\ProgramData\C\include';
	coinlibdir     = 'C:\ProgramData\C\lib';
	% --------------------------------------------

	fprintf('Compiling GRD (first-time use)... ');
	dir = fileparts(which(mfilename));
	
	libdir     = [dir filesep '..' filesep 'source' filesep 'library'];
	qpbodir    = [dir filesep '..' filesep 'thirdparty' filesep 'QPBO'];
	hocrdir    = [dir filesep '..' filesep 'thirdparty' filesep 'HOCR'];
	maxflowdir = [dir filesep '..' filesep 'thirdparty' filesep 'maxflow-v3.01.src'];
	petterdir  = [dir filesep '..' filesep 'thirdparty' filesep 'Petter'];
	
	mex('grd_mex.cpp', ...
		['-I"' libdir '"'], ...
		['-I"' qpbodir '"'], ...
		['-I"' hocrdir '"'], ...
		['-I"' maxflowdir '"'], ...
		['-I"' coinincludedir '"'], ...
		['-L"' coinlibdir '"'], ...
		['"' libdir filesep 'PseudoBoolean.cpp"'],...
		['"' libdir filesep 'PseudoBoolean_minimize.cpp"'],...
		['"' libdir filesep 'PseudoBoolean_complete.cpp"'],...
		['"' libdir filesep 'PseudoBoolean_create_g.cpp"'],...
		['"' libdir filesep 'PseudoBoolean_heuristic.cpp"'],...
		['"' libdir filesep 'PseudoBoolean_minimize.cpp"'],...
		['"' libdir filesep 'PseudoBoolean_minimize_lp.cpp"'],...
		['"' libdir filesep 'PseudoBoolean_minimize_reduction.cpp"'],...
		['"' libdir filesep 'PseudoBoolean_reduce.cpp"'],...
		['"' libdir filesep 'GeneratorPseudoBoolean.cpp"'],...
		['"' qpbodir filesep 'QPBO.cpp"'],...
		['"' qpbodir filesep 'QPBO_extra.cpp"'],...
		['"' qpbodir filesep 'QPBO_maxflow.cpp"'],...
		['"' qpbodir filesep 'QPBO_postprocessing.cpp"'],...
		['"' maxflowdir filesep 'maxflow.cpp"'],...
		['"' maxflowdir filesep 'graph.cpp"'],...
		['"' petterdir filesep 'Petter-Color.cc"'],...
		'-lClp', ...
		'-lCoinUtils' ...
	);
	fprintf('done!\n');
	
	% Now call the compiled function
	[varargout{1:nargout}] = feval(mfilename, varargin{:});
end
